### ISSUE TITLE
[Feature] Timed commands

### ISSUE THREAD

**Issue by Bob1nz** [JayWood/WooMinecraft#5]
A nice feature would be to have a second set of commands to run after a configurable amount of time.

For example
VIP 
$5.00 for 30 days

after purchase run the command /perm give %s VIP.node

then after 30 days it would automatically send the second command /perm remove %s VIP.node

**Comment by brainscript** [comment]
This works with the built-in features of mostly any permissions system. :jack_o_lantern: In **PermissionsEx** for example this would look like that: `pex user %s group add VIP "" 2592000` The huge number is the :hourglass: lifetime in seconds.

I don't see any reason why **WooMinecraft** should handle that. :stuck_out_tongue_winking_eye:

**Comment by ApfelUser** [comment]
@Bob1nz & @brainscript you are on the wrong repository. The new one is here:

[WooMinecraft/WooMinecraft](https://github.com/WooMinecraft/WooMinecraft)

**Comment by JayWood** [comment]
@brainscript the way the code 'used to' work was the command was sent TO the MC server, so I do see your point.  You could just do that command, instead of having a dev to edit the java code.

I'm going to close all tickets located here sometime today after work so please reference any tickets to the new repo.  We're doing some great work there!
